version: '3'
services:

  neueda-tinyapi:
    image: neuedaapplicanttest
    ports: ["8080:8080"]
    networks: [tinyurl-mysql]
    depends_on:
        - mysqldb
        
  mysqldb:
    image: mysql/mysql-server:8.0
    networks: [tinyurl-mysql]
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=urlprocessschema
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports: ["3306:3306"]
      
networks:
  tinyurl-mysql:
      
  

 
